### PR TITLE
Fix SteamVR Crash

### LINKED ISSUE #94: OpenXRTest Editor Crashes When Running Valve Index using Vulkan RHI
Running OpenXRTest Editor.exe with Valve Index results in a runtime exception.

**Repro**
1. Connect your Valve Index device and open the SteamVR app
1. Open Editor.exe with Vulkan rendering enabled (--rhi=vulkan)

**Expected Result**
Editor opens without crashing

**Actual Result**
xrEnumerateSwapchainImages throws an exception
Honestly, this might be a bug with OpenXR as [xrEnumerateSwapchainImages](https://registry.khronos.org/OpenXR/specs/1.0/man/html/xrEnumerateSwapchainImages.html) is supposed to return an error code (it doesn't state it's possible to throw an exception)

```
 	vrclient_x64.dll!00007ff8e015f3df()	Unknown
 	vrclient_x64.dll!00007ff8dff1ae48()	Unknown
 	vrclient_x64.dll!00007ff8dfef5b73()	Unknown
 	OpenXRVk.dll!xrEnumerateSwapchainImages()	C++
>	OpenXRVk.dll!OpenXRVk::SwapChain::InitInternal() Line 212	C++
 	[Inline Frame] XR.dll!XR::SwapChain::Init(const XR::SwapChain::Descriptor &) Line 26	C++
 	XR.dll!XR::System::CreateSwapChain() Line 102	C++
 	Atom_RHI_Vulkan.Private.dll!AZ::Vulkan::Device::InitializeLimits() Line 412	C++
 	Atom_RPI.Editor.dll!AZ::RHI::Device::Init(AZ::RHI::PhysicalDevice & physicalDevice) Line 94	C++
 	Atom_RPI.Editor.dll!AZ::RHI::RHISystem::InitInternalDevice() Line 166	C++
 	Atom_RPI.Editor.dll!AZ::RHI::RHISystem::InitDevice() Line 37	C++
 	Atom_RPI.Editor.dll!AZ::RPI::RPISystem::Initialize(const AZ::RPI::RPISystemDescriptor & rpiSystemDescriptor) Line 98	C++
 	Atom_RPI.Editor.dll!AZ::RPI::RPISystemComponent::Activate() Line 130	C++
 	[Inline Frame] EditorLib.dll!AZ::Entity::ActivateComponent(AZ::Component &) Line 399	C++
 	EditorLib.dll!AZ::ModuleManager::ActivateEntities(const AZStd::vector<AZStd::shared_ptr<AZ::ModuleDataImpl>,AZStd::allocator> & modulesToInit) Line 760	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::INVOKE(void(AZ::EntityEvents::*)(const AZ::EntityId &) &) Line 177	C++
 	[Inline Frame] EditorLib.dll!AZStd::invoke(void(AZ::EntityEvents::*)(const AZ::EntityId &) &) Line 54	C++
 	[Inline Frame] EditorLib.dll!AZ::EBusEventProcessingPolicy::Call(void(AZ::EntityEvents::*)(const AZ::EntityId &) &) Line 437	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AZ::EntityEvents,AZ::EntityEvents,1,1>::Dispatcher<AZ::EBus<AZ::EntityEvents,AZ::EntityEvents>>::Event<void (__cdecl AZ::EntityEvents::*)(AZ::EntityId const &),AZ::EntityId &>(const AZ::EntityId & id, void(AZ::EntityEvents::*)(const AZ::EntityId &) && func, AZ::EntityId & <args_0>) Line 146	C++
 	EditorLib.dll!AZ::Entity::Activate() Line 214	C++
 	EditorLib.dll!AzFramework::Application::StartCommon(AZ::Entity * systemEntity) Line 220	C++
 	EditorLib.dll!AzToolsFramework::ToolsApplication::StartCommon(AZ::Entity * systemEntity) Line 328	C++
 	EditorLib.dll!EditorInternal::EditorToolsApplication::StartCommon(AZ::Entity * systemEntity) Line 95	C++
 	EditorLib.dll!AzFramework::Application::Start(const AZ::ComponentApplication::Descriptor & descriptor, const AZ::ComponentApplication::StartupParameters & startupParameters) Line 212	C++
 	EditorLib.dll!AzToolsFramework::ToolsApplication::Start(const AZ::ComponentApplication::Descriptor & descriptor, const AZ::ComponentApplication::StartupParameters & startupParameters) Line 313	C++
 	EditorLib.dll!EditorInternal::EditorToolsApplication::Start() Line 108	C++
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3977	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++

```

### PR DESCRIPTION
**Pull request by AMZN-Gene**
Adding sRGB color space as a swapchain option; this allowed rendering to work on my Valve Index (SteamVR device)

Not a complete fix, because the colors look washed out (pushed towards white), likely because the swapchain is using sRGB, but the colors are still being sent in linear color space.
Notice how the table is very washed out
image

Fixes #94

### CODE REVIEW

File: Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp [hunk 1]
```diff
@@ -241,7 +241,7 @@ namespace OpenXRVk
     VkFormat SwapChain::SelectColorSwapChainFormat(const AZStd::vector<int64_t>& runtimeFormats) const
     {
         // List of supported color swapchain formats.
-        constexpr int64_t SupportedColorSwapchainFormats[] = { VK_FORMAT_B8G8R8A8_UNORM, VK_FORMAT_R8G8B8A8_UNORM };
+        constexpr int64_t SupportedColorSwapchainFormats[] = { VK_FORMAT_B8G8R8A8_UNORM, VK_FORMAT_R8G8B8A8_UNORM, VK_FORMAT_R8G8B8A8_SRGB };
```
Comment (laoyigrace) [inline Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp:244]: On the VR, I also encountered this problem, you can't completely modify this problem, in the VR picture is abnormal.

Comment (AMZN-Gene) [reply Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp:244]: Yeah, I think I need to find a way so that the rest of the rendering pipelines render targets also use sRGB color-space if the device requires sRGB. Otherwise, we could explicitly do gamma correction in the shader code. Would love @o3de/sig-graphics-audio feedback. At the very least, this PR allows for testing on device, which is better than nothing :D

**Review by moudgils — APPROVED** [review]
This is fine for now but obviously not correct. In order for it to work correctly we will need to add support to spit out color in sRGB space based on the swapchain color format. We will probably need to use a shader option to drive this work in the shader. This PR can be merged in as it fixes the crash but we should open a new PR to add sRGB support for the VR pipeline at the very least.

**Comment by AMZN-Gene** [comment]
> This is fine for now but obviously not correct. In order for it to work correctly we will need to add support to spit out color in sRGB space based on the swapchain color format. We will probably need to use a shader option to drive this work in the shader. This PR can be merged in as it fixes the crash but we should open a new PR to add sRGB support for the VR pipeline at the very least.

Should we convert this GHI question into the feature request you’re talking about here? 
https://github.com/o3de/o3de-extras/issues/76

File: Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp (hunk 1 above)
Comment (laoyigrace) [reply Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp:244]: Got it

**Review by invertednormal — APPROVED** [review]
