### PR TITLE
Change maximum size of AMENT_PATH, fixed Qt rendering of assets.

### LINKED ISSUE #533: Too long AMENT_PREFIX_PATH causes problems
Too long AMENT_PREFIX_PATH (5096) causes that AMENT_PREFIX_PATH is ignored. 
What is more it produces misleading warning :
```
<14:49:51> [Error] (UrdfAssetMap) - AMENT_PREFIX_PATH is not found.
<14:49:51> (ResolveAssetPath) - ResolveAssetPath with model://husky_description/meshes/top_plate.dae

<14:49:51> [Warning] (CopyAssetForURDF) - There is no resolved path for model://husky_description/meshes/top_plate.dae
<14:49:51> (ResolveAssetPath) - ResolveAssetPath with model://husky_description/meshes/top_plate.stl

<14:49:51> [Warning] (CopyAssetForURDF) - There is no resolved path for model://husky_description/meshes/top_plate.stl
<14:49:51> (ResolveAssetPath) - ResolveAssetPath with model://husky_description/meshes/top_chassis.dae

<14:49:51> [Warning] (CopyAssetForURDF) - There is no resolved path for model://husky_description/meshes/top_chassis.dae
<14:49:51> (ResolveAssetPath) - ResolveAssetPath with model://husky_description/meshes/user_rail.dae

<14:49:51> [Warning] (CopyAssetForURDF) - There is no resolved path for model://husky_description/meshes/user_rail.dae
<14:49:51> (ResolveAssetPath) - ResolveAssetPath with model://husky_description/meshes/wheel.dae

<14:49:51> [Warning] (CopyAssetForURDF) - There is no resolved path for model://husky_description/meshes/wheel.dae
<14:49:51> (ResolveAssetPath) - ResolveAssetPath with model://husky_description/meshes/bumper.dae

<14:49:51> [Warning] (CopyAssetForURDF) - There is no resolved path for model://husky_description/meshes/bumper.dae
<14:49:51> (ResolveAssetPath) - ResolveAssetPath with model://husky_description/meshes/base_link.dae

<14:49:51> [Warning] (CopyAssetForURDF) - There is no resolved path for model://husky_description/meshes/base_link.dae

```

Also wizard page gives mixed signals with green ticks:
image

### PR DESCRIPTION
**Pull request by michalpelka**
fixes #533

### CODE REVIEW

File: Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp [hunk 1]
```diff
@@ -98,30 +98,53 @@ namespace ROS2
...
+
+        if (assetSourcePath)
+        {
+            m_table->setItem(
+                i, Columns::SourceAsset, createCell(true, QString::fromUtf8(assetSourcePath->data(), assetSourcePath->size())));
+        }
+        else
+        {
+            m_table->setItem(i, Columns::SourceAsset, createCell(false, tr("Not found")));
+        }
```
Comment (lumberyard-employee-dm) [inline Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp:146]: I noticed the path can be empty in some cases in which case it also outputs a green checkmark instead of a red X.

Could we add a check to make sure the string isn't empty as well?
```suggestion
        if (assetSourcePath && !assetSourcePath->empty())
        {
            m_table->setItem(
                i, Columns::SourceAsset, createCell(true, QString::fromUtf8(assetSourcePath->data(), assetSourcePath->size())));
        }
        else
        {
            m_table->setItem(i, Columns::SourceAsset, createCell(false, tr("Not found")));
        }
```

**Review by lemonade-dm — APPROVED** [review]
It looks like you have an issue with DCO signoff

**Comment by michalpelka** [comment]
I do not know why but applying review suggestion signs with my private email.

**Comment by michalpelka** [comment]
Fixed.

**Review by adamdbrw — APPROVED** [review]
