### PR TITLE
Use ROS 2 clock for sensor triggering

### LINKED ISSUE #805: Inconsistent way to trigger sensors in ROS2 Gem
**Describe the bug**
ROS2 Gem has two ways to trigger sensors :
 - [TickBasedSource](https://github.com/o3de/o3de-extras/blob/d2888c1be6f339d323316f46633d46e35816864d/Gems/ROS2/Code/Include/ROS2/Sensor/Events/TickBasedSource.h#L20) 
 - [PhysicsBasedSource](https://github.com/o3de/o3de-extras/blob/d2888c1be6f339d323316f46633d46e35816864d/Gems/ROS2/Code/Include/ROS2/Sensor/Events/PhysicsBasedSource.h)
Both those wrap OnTickBus and SceneEvents::OnSceneSimulationFinishHandler.
Those calls implementation of sensor measurements.
Problem is that both implementations do not respect simulation time
```cpp
        m_onSceneSimulationEventHandler = AzPhysics::SceneEvents::OnSceneSimulationFinishHandler(
            [this](AzPhysics::SceneHandle sceneHandle, float deltaTime)
            {
                m_sourceEvent.Signal(sceneHandle, deltaTime);
            });
```
and 
```cpp
    void TickBasedSource::OnTick(float deltaTime, AZ::ScriptTimePoint time)
    {
        m_sourceEvent.Signal(deltaTime, time);
    }
```
Those delta times are not the same, one is update dt time of PhysX second one it wall time. 
It should be consistent and use ROS2 Gem API to get time:
```cpp
        m_onSceneSimulationEventHandler = AzPhysics::SceneEvents::OnSceneSimulationFinishHandler(
            [this, ros2Interface](AzPhysics::SceneHandle sceneHandle, float deltaTime)
            {
                const auto simulationTime = ros2Interface->GetROSTimestamp();

                float deltaSimTime = ROS2Conversions::GetTimeDifference(m_lastSimulationTime, simulationTime);
                m_sourceEvent.Signal(sceneHandle, deltaTime);
            });
```
**Assets required**
N/A

**Steps to reproduce**
- Use "SteadyClock":
```
{
    "O3DE":
    {
        "InputSystem":
        {
            "Mouse":
            {
                "CaptureMouseCursor": false
            }
        },
        "ROS2":
        {
            "SteadyClock" : true,
            "Camera":
            {
                "AllowPipelineModification": true
            }
        }
    }
}
```
- Set PhysX engine to be very non-realtime:
image
- Add camera and Imu component.
- Set Imu freq to 100 hz and camera 60 fps
- Make sure App runs at 60 fps.
Measure hz of messages using ros2 topic hz:

```
ros2 topic hz /Camera/camera_image_color --use-sim-time
ros2 topic hz /Cannonball/imu --use-sim-time
ros2 topic hz /Camera/camera_image_color
ros2 topic hz /Cannonball/imu
```

**Expected behavior**
| topic      | Hz with --use-sim-time |  Hz without --use-sim-time |
| -------      | --------------------------------- |  ------------------------------------- |
| imu        | 100                                   | 6                                              |
| camera  | ~60                                  | ~ 3.6                                       |

**Actual behavior**
| topic      | Hz with --use-sim-time |  Hz without --use-sim-time |
| -------      | --------------------------------- |  ------------------------------------- |
| imu        | 100                                   | 6                                              |
| camera  | 997                                   | 60                                           |

**Screenshots/Video**

https://github.com/user-attachments/assets/bdf55f16-1d02-43f7-8d7c-43b4301435c8

**Found in Branch**
development, main

### PR DESCRIPTION
**Pull request by michalpelka**
## What does this PR do?

This PR fixes two minor things in sensors triggering:
- it reintroduced removed by this PR median filter for FPS. It will prevent drops in camera frequency without frame limiter, as explained in #804 .
- it uses selected ROS 2 time source to trigger sensors, what  will resolve #805 

## How was this PR tested?

It was cherry picked against stable and tested in response to #804.
I've used test branch that logs sensor triggers (https://github.com/RobotecAI/o3de-extras/tree/mp/trigger_noted)
And script to visualize : https://gist.github.com/michalpelka/3f2c66f16d20ba714c6389d5cd173032

Without filter:
NoFiltering
With filtering
WithMedianFilter

You can see that triggers fro camera (green dots) are spaced evenly for code using median filter.
**Note** this is minor issue, since it can cause:
- too low frequency use case without frame limiter and request for high FPS ROS 2 camera.
- most simulation are using `\clock` topic so inconsistency in wall time is not that big deal.

### CODE REVIEW

File: Gems/ROS2/Code/Include/ROS2/Sensor/Events/EventSourceAdapter.h [hunk 1]
```diff
@@ -180,10 +180,10 @@ namespace ROS2
             {
                 return false;
             }
-
             const float sourceFrequencyEstimation = 1.0f / sourceDeltaTime;
             const float numberOfFrames =
                 m_adaptedFrequency <= sourceFrequencyEstimation ? (sourceFrequencyEstimation / m_adaptedFrequency) : 1.0f;
+            AZ_Printf("EventSourceAdapter", "Number of frames: %f", numberOfFrames);
```
Comment (michalpelka) [inline Gems/ROS2/Code/Include/ROS2/Sensor/Events/EventSourceAdapter.h:186]:
```suggestion
```

File: Gems/ROS2/Code/Source/Sensor/Events/PhysicsBasedSource.cpp [hunk 2]
```diff
@@ -23,10 +25,16 @@ namespace ROS2
     void PhysicsBasedSource::Start()
     {
         m_onSceneSimulationEventHandler.Disconnect();
+        const auto* ros2Interface = ROS2Interface::Get();
+        AZ_Assert(ros2Interface, "ROS2 interface is not initialized.");
```
Comment (pijaro) [inline Gems/ROS2/Code/Source/Sensor/Events/PhysicsBasedSource.cpp:29]: Nit :wink: 
```suggestion
        AZ_Assert(ros2Interface, "ROS 2 interface is not initialized.");
```

**Review by pijaro — APPROVED** [review]
Good changes, approved with a minor nitpick.
