### PR TITLE
Fix SkidSteeringDriveModel

### LINKED ISSUE #615: Fix skid steering drive model parameters
Wheelbase and track
[Wheelbase definition](https://en.wikipedia.org/wiki/Wheelbase)

The speed of the wheels depends primarily on the distance between the wheels in the skid steering drive model. In o3de-extras implementation, the skid steering drive model uses _wheelbase_ parameter, but it does not use _track_ parameter.
https://github.com/o3de/o3de-extras/blob/153d83cbf09695c2e141e5016ba7a3ba35ef5709/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp#L162

Therefore I believe the terms are used incorrectly for this model. The configuration is shared with Ackermann implementation, in which terms are used correctly.  Please keep in mind, that changing the name in the code might influence all available prefabs using this drive model.

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
## What does this PR do?

This PR fixes some issues in _SkidSteeringDriveModel_ implementation. Both the method for applying the rotation to wheels based on the requested model movement and the method for calculating the model's movement based on the wheels' rotation were refactored.
- The track parameter is used instead of the wheelbase parameter for calculation (Closes #615), the naming is also unified and fixed.
- The same distance between wheels is used in the codebase (it was two times bigger while [getting the speed](https://github.com/o3de/o3de-extras/blob/d9fc445a72a30ed683cf6cb18dfa8b3a3e762f6a/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp#L60) than while [applying the speed](https://github.com/o3de/o3de-extras/blob/d9fc445a72a30ed683cf6cb18dfa8b3a3e762f6a/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp#L162). This part was working correctly only for robots with two wheels per axle, now the code is more readable and works for any number of wheels.
- One buffer instead of [two separate ones](https://github.com/o3de/o3de-extras/blob/d9fc445a72a30ed683cf6cb18dfa8b3a3e762f6a/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h#L55) is used to cache data; there is no recalculation of some of it in [every step](https://github.com/o3de/o3de-extras/blob/d9fc445a72a30ed683cf6cb18dfa8b3a3e762f6a/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp#L160).
- The correct number of axles is used in the calculation (non-drivable axles were taken into consideration [previously](https://github.com/o3de/o3de-extras/blob/d9fc445a72a30ed683cf6cb18dfa8b3a3e762f6a/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp#L83) ).
- Segfault triggered when the [number of wheels == 1](https://github.com/o3de/o3de-extras/blob/153d83cbf09695c2e141e5016ba7a3ba35ef5709/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp#L161) is removed.
- The names such as `axis` and `axle` are unified along the codebase and used correctly.

## How was this PR tested?

- create an empty level
- import robot with SkidSteering (ROSbot in my case)
- add `ROS2 Wheel Odometry Sensor`
- send commands to move the robot via ROS2 and echo the odometry in another terminal - the values should be approximately the same
```bash
ros2 topic pub -r 10 /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.5, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 1.0}}" 
ros2 topic echo /odom
```

### CODE REVIEW

**Review by adamkrawczyk — APPROVED** [review]

File: Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp [hunk 1]
```diff
@@ -38,72 +38,95 @@ namespace ROS2::VehicleDynamics
...
+                {
+                    m_wheelsCache.emplace_back(AZStd::move(column));
+                }
+            }
+        }
+
+        m_initialized = true;
+    }
+
+    SkidSteeringDriveModel::SkidSteeringWheelData SkidSteeringDriveModel::ProduceWheelColumn(
```
Comment (adamkrawczyk) [inline Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp:85]: Consider move semantic for `SkidSteeringDriveModel` to optimize return. But since this is not executed periodically it's not crucial. Nice to have.

File: Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h [hunk 2]
```diff
@@ -37,25 +37,43 @@ namespace ROS2::VehicleDynamics
         AZStd::pair<AZ::Vector3, AZ::Vector3> GetVelocityFromModel() override;
 
     private:
+        // Data collected once and cached for the reuse
```
Comment (adamdbrw) [inline Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h:40]: This comment should be next to the member (m_wheelsCache instead). 
Instead, describe what the structure is for here.

File: Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h [hunk 3]
```diff
@@ -37,25 +37,43 @@ namespace ROS2::VehicleDynamics
...
+        //! It can be thought of as a column of the Jacobian matrix of the mechanical system. Jacobian matrix for this model is a matrix
+        //! of size 2 x number of wheels. This function returns elements of column that corresponds to the given wheel and cache
+        //! necessary data to find the wheel's rotation as a scalar.
+        //! @param wheelId - id of the currently processed wheel in the axle vector
         //! @param axle - the wheel's axle configuration
-        //! @param axisCount - number of axles in the vehicle
-        //! @returns A tuple containing of :
-        //!  - pointer to WheelControllerComponent (API to query for wheel's ration speed),
+        //! @param axlesCount - number of axles in the vehicle
+        //! @returns A structure containing of:
```
Comment (adamdbrw) [inline Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h:64]: This documentation should link to the structure documentation, here just link to the structure.

File: Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h [hunk 4]
```diff
@@ -37,25 +37,43 @@ namespace ROS2::VehicleDynamics
...
+            float dX{ 0.0f }; // wheel's contribution to vehicle's linear movement
+            float dPhi{ 0.0f }; // wheel's contribution to vehicle's rotational movement
+            AZ::Vector3 axis{ AZ::Vector3::CreateZero() }; // rotation axis of the wheel
+        };
+        AZStd::vector<SkidSteeringWheelData> m_wheelsCache;
+        bool m_initialized = false;
+
+        //! Collect all necessary data to compute the impact of wheels on the vehicle's velocity.
+        //! The data is stored in cache and reused.
+        void InitializeCache();
```
Comment (adamdbrw) [inline Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h:55]: Better call it ComputeWheelVelocityImpact or similar - focus on semantics (What happens when this function is called) and not implementation (Cache). Cache is a bit misleading here.

File: Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp (hunk 1 above)
Comment (jhanca-robotecai) [reply Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp]: Please correct me if I am wrong, but the temporary in `SkidSteeringDriveModel::ProduceWheelColumn` is implicitly treated as an rvalue in the return statement by the compiler's RVO.

Comment (adamkrawczyk) [reply Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp]: You are right! I have checked and according to the docs this is a perfect candidate for rvo.

**Review by michalpelka — APPROVED** [review]

**Comment by jhanca-robotecai** [comment]
Rebased and force-pushed after #609 was merged to resolve conflicts - only conflicts in one comment found, hence no need for another review.

**Review by adamdbrw — APPROVED** [review]
LGTM, good work!
